version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: mudassirdoc12/flask-backend:latest  # Specify the backend image
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: mudassirdoc12/express-frontend:latest  # Specify the frontend image
    ports:
      - "3001:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge