version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: mudassirdoc12/flask-backend:latest
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: mudassirdoc12/express-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge