version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
    image: mudassirdoc12/flask-backend:latest
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:  # ✅ Fixed: now under services
    platform: linux/amd64
    build:
      context: ./frontend
    image: mudassirdoc12/express-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:5000

networks:
  app-network:
    driver: bridge